on:
  push: {}
  pull_request: {}
  workflow_call:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # for commit linting
          persist-credentials: false
      - uses: webiny/action-conventional-commits@v1.4.2
      - uses: actions/cache@v6
        with:
          path: |
            .bin/
            target/
            ~/.cargo/
          # cargo-run-bin refers to the following step
          key: ${{ runner.os }}_cargo-run-bin_${{ hashFiles('Cargo.toml', 'Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}_cargo-run-bin_
            ${{ runner.os }}_
      - run: cargo install cargo-run-bin
      - run: cargo bin makers ci_checks
